In [1]:
import pandas as pd

df = pd.read_csv(r'G:\campusx ML algo code\Ecommerce data\data.csv', encoding='ISO-8859-1')

In [2]:
df.shape

(541909, 8)

In [3]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [4]:
df = df.drop(columns='StockCode')

In [5]:
df = df.dropna(subset='CustomerID')

In [6]:
df.isnull().sum()

InvoiceNo      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [7]:
df['Quantity'].describe()

count    406829.000000
mean         12.061303
std         248.693370
min      -80995.000000
25%           2.000000
50%           5.000000
75%          12.000000
max       80995.000000
Name: Quantity, dtype: float64

In [8]:
df = df[df['Quantity']>0]

In [9]:
df.dtypes

InvoiceNo          str
Description        str
Quantity         int64
InvoiceDate        str
UnitPrice      float64
CustomerID     float64
Country            str
dtype: object

In [10]:
df['CustomerID'] = df['CustomerID'].astype('str')

In [11]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [12]:
df.dtypes

InvoiceNo                 str
Description               str
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID                str
Country                   str
dtype: object

In [13]:
df.describe(include='all')

,InvoiceNo,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
count,397924,397924,397924.000000,397924,397924.000000,397924,397924
unique,18536,3877,NaN,NaN,NaN,4339,37
top,576339,WHITE HANGING HEART T-LIGHT HOLDER,NaN,NaN,NaN,17841.0,United Kingdom
freq,542,2028,NaN,NaN,NaN,7847,354345
mean,NaN,NaN,13.021823,2011-07-10 23:43:36.912476,3.116174,NaN,NaN
min,NaN,NaN,1.000000,2010-12-01 08:26:00,0.000000,NaN,NaN
25%,NaN,NaN,2.000000,2011-04-07 11:12:00,1.250000,NaN,NaN
50%,NaN,NaN,6.000000,2011-07-31 14:39:00,1.950000,NaN,NaN
75%,NaN,NaN,12.000000,2011-10-20 14:33:00,3.750000,NaN,NaN
max,NaN,NaN,80995.000000,2011-12-09 12:50:00,8142.750000,NaN,NaN
std,NaN,NaN,180.420210,NaN,22.096788,NaN,NaN

In [14]:
df['Total_Amount'] = df['Quantity'] * df['UnitPrice']

In [15]:
df.head()

,InvoiceNo,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Total_Amount
0,536365,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [16]:
df['Year'] = df['InvoiceDate'].dt.year
df['Month'] = df['InvoiceDate'].dt.month
df['Date'] = df['InvoiceDate'].dt.date
df['Day_Name'] = df['InvoiceDate'].dt.day_name()

In [24]:
res1 = df.groupby(['Country'])['Total_Amount'].sum().reset_index()
res1.sort_values(by='Total_Amount',ascending=True)

                 Country  Total_Amount
28          Saudi Arabia       145.920
2                Bahrain       548.400
8         Czech Republic       826.740
27                   RSA      1002.310
4                 Brazil      1143.600
11    European Community      1300.250
21             Lithuania      1661.060
20               Lebanon      1693.880
34  United Arab Emirates      1902.280
36           Unspecified      2667.070
22                 Malta      2725.590
33                   USA      3580.390
5                 Canada      3666.380
16               Iceland      4310.000
15                Greece      4760.520
17                Israel      7221.690
25                Poland      7334.650
1                Austria     10198.680
7                 Cyprus     13590.380
18                 Italy     17483.240
9                Denmark     18955.340
6        Channel Islands     20450.440
29             Singapore     21279.290
12               Finland     22546.080
26              Portugal     33439.890
24                Norway     36165.440
19                 Japan     37416.370
31                Sweden     38378.330
3                Belgium     41196.340
32           Switzerland     56443.950
30                 Spain     61577.110
0              Australia    138521.310
13                France    209024.050
14               Germany    228867.140
10                  EIRE    265545.900
23           Netherlands    285446.340
35        United Kingdom   7308391.554